<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.951" timestamp="2024-07-25T15:55:18.972860" hostname="acernb001"><testcase classname="lesson_23.tests.test_demo" name="test_wait_more_30_sec[chromium]" time="0.767"><error message="failed on setup with &quot;playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8000/&#10;Call log:&#10;navigating to &quot;http://127.0.0.1:8000/&quot;, waiting until &quot;load&quot;&quot;">get_browser = &lt;Browser type=&lt;BrowserType name=chromium executable_path=/home/oleg/.cache/ms-playwright/chromium-1117/chrome-linux/chrome&gt; version=125.0.6422.26&gt;
request = &lt;SubRequest 'desktop_app' for &lt;Function test_wait_more_30_sec[chromium]&gt;&gt;

    @fixture(scope='session')
    def desktop_app(get_browser, request):
        base_url = request.config.getini("base_url")
        app = App(get_browser, base_url=base_url, **BROWSER_OPTIONS)
&gt;       app.goto("/")

../conftest.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../page_object/application.py:31: in goto
    self.page.goto(self.base_url + endpoint)
../../.venv/lib/python3.10/site-packages/playwright/sync_api/_generated.py:8686: in goto
    self._sync(
../../.venv/lib/python3.10/site-packages/playwright/_impl/_page.py:519: in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
../../.venv/lib/python3.10/site-packages/playwright/_impl/_frame.py:145: in goto
    await self._channel.send("goto", locals_to_params(locals()))
../../.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7df1bf8a13f0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7df1bed783a0&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8000/
E           Call log:
E           navigating to "http://127.0.0.1:8000/", waiting until "load"

../../.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py:514: Error</error></testcase></testsuite></testsuites>